workflows:
  android-workflow:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate Launcher Icons
        script: |
          dart run flutter_launcher_icons
      - name: Decode Keystore
        script: |
          mkdir -p android/app/keystore
          echo $CM_KEYSTORE | base64 --decode > android/app/keystore/upload-keystore.jks
      - name: Create key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=../app/keystore/upload-keystore.jks" >> android/key.properties
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - miosegundamano9@gmail.com
        notify:
          success: true
          failure: true
