name: dont_touch_red
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^7.0.0
  audioplayers: ^6.1.1
  confetti: ^0.7.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pngtree-emerald-diamond-accessory-transparent-png-image_6674306.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/pngtree-emerald-diamond-accessory-transparent-png-image_6674306.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
